CREATE TABLE print_profiles (
    id                                      INTEGER PRIMARY KEY AUTOINCREMENT,
    filament_id                             INTEGER NOT NULL REFERENCES filaments(id),
    spool_id                                INTEGER REFERENCES spools(id),
    name                                    TEXT NOT NULL,
    print_speed_mm_s                        INTEGER,

    nozzle_temp_c                           INTEGER NOT NULL,
    nozzle_temp_initial_c                   INTEGER,
    nozzle_temp_range_high_c                INTEGER,
    nozzle_temp_range_low_c                 INTEGER,
    cool_plate_temp_c                       INTEGER,
    cool_plate_temp_initial_c               INTEGER,
    hot_plate_temp_c                        INTEGER,
    hot_plate_temp_initial_c                INTEGER,
    textured_plate_temp_c                   INTEGER,
    textured_plate_temp_initial_c           INTEGER,
    eng_plate_temp_c                        INTEGER,
    eng_plate_temp_initial_c                INTEGER,
    supertack_plate_temp_c                  INTEGER,
    supertack_plate_temp_initial_c          INTEGER,

    fan_min_speed_pct                       INTEGER,
    fan_max_speed_pct                       INTEGER,
    additional_cooling_fan_speed_pct        INTEGER,
    close_fan_first_x_layers                INTEGER,
    complete_print_exhaust_fan_speed_pct    INTEGER,
    during_print_exhaust_fan_speed_pct      INTEGER,
    chamber_temperature_c                   INTEGER,
    cooling_perimeter_transition_distance_mm REAL,
    cooling_slowdown_logic                  TEXT,
    enable_overhang_bridge_fan              INTEGER,
    fan_cooling_layer_time_s                INTEGER,
    first_x_layer_fan_speed_pct             INTEGER,
    full_fan_speed_layer                    INTEGER,
    no_slow_down_for_cooling_on_outwalls    INTEGER,
    overhang_fan_speed_pct                  INTEGER,
    overhang_fan_threshold                  TEXT,
    overhang_threshold_participating_cooling TEXT,
    override_process_overhang_speed         INTEGER,
    pre_start_fan_time_s                    INTEGER,
    reduce_fan_stop_start_freq              INTEGER,
    slow_down_for_layer_cooling             INTEGER,
    slow_down_layer_time_s                  INTEGER,
    slow_down_min_speed_mm_s                INTEGER,
    activate_air_filtration                 INTEGER,

    retraction_mm                           REAL,
    retraction_speed_mm_s                   REAL,
    deretraction_speed_mm_s                 REAL,
    retraction_minimum_travel_mm            REAL,
    retract_before_wipe                     TEXT,
    retract_restart_extra_mm                REAL,
    retract_when_changing_layer             INTEGER,
    retraction_distances_when_cut_mm        REAL,
    retract_length_nc_mm                    REAL,
    long_retractions_when_cut               INTEGER,
    long_retractions_when_ec                INTEGER,
    retraction_distances_when_ec_mm         REAL,

    wipe_enabled                            INTEGER,
    wipe_distance_mm                        REAL,
    z_hop_mm                                REAL,
    z_hop_type                              TEXT,
    change_length_mm                        REAL,
    change_length_nc_mm                     REAL,
    cooling_before_tower_s                  INTEGER,
    minimal_purge_on_wipe_tower_mm3         REAL,
    prime_volume_mm3                        REAL,
    prime_volume_nc_mm3                     REAL,
    ramming_travel_time_s                   REAL,
    ramming_travel_time_nc_s                REAL,
    ramming_volumetric_speed_mm3_s          REAL,
    ramming_volumetric_speed_nc_mm3_s       REAL,
    tower_interface_pre_extrusion_dist_mm   REAL,
    tower_interface_pre_extrusion_length_mm REAL,
    tower_interface_print_temp_c            INTEGER,
    tower_interface_purge_volume_mm3        REAL,
    tower_ironing_area_mm2                  REAL,
    flush_temp_c                            INTEGER,
    flush_volumetric_speed_mm3_s            REAL,

    adaptive_volumetric_speed               INTEGER,
    max_volumetric_speed_mm3_s              REAL,
    bridge_speed_mm_s                       REAL,
    enable_overhang_speed                   INTEGER,
    overhang_14_speed_mm_s                  REAL,
    overhang_24_speed_mm_s                  REAL,
    overhang_34_speed_mm_s                  REAL,
    overhang_44_speed_mm_s                  REAL,
    overhang_totally_speed_mm_s             REAL,
    circle_compensation_speed_mm_s          REAL,
    velocity_adaptation_factor              REAL,
    volumetric_speed_coefficients           TEXT,

    density_g_cm3                           REAL,
    diameter_mm                             REAL,
    diameter_limit_mm                       REAL,
    shrink_pct                              TEXT,
    soluble                                 INTEGER,
    is_support                              INTEGER,
    printable                               INTEGER,
    adhesiveness_category                   INTEGER,
    impact_strength_z                       REAL,
    cost_per_kg                             REAL,
    flow_ratio                              REAL,
    extruder_variant                        TEXT,
    slicer_notes                            TEXT,
    required_nozzle_hrc                     INTEGER,

    enable_pressure_advance                 INTEGER,
    pressure_advance                        REAL,

    drying_ams_limitations                  TEXT,
    drying_ams_heat_distortion_temp_c       INTEGER,
    drying_ams_temp_c                       INTEGER,
    drying_ams_time_h                       REAL,
    drying_chamber_bed_temp_c               INTEGER,
    drying_chamber_time_h                   REAL,
    drying_cooling_temp_c                   INTEGER,
    drying_softening_temp_c                 INTEGER,
    softening_temp_c                        REAL,

    scarf_seam_type                         TEXT,
    scarf_gap_pct                           TEXT,
    scarf_height_pct                        TEXT,
    scarf_length_mm                         REAL,

    hole_coef_1                             REAL,
    hole_coef_2                             REAL,
    hole_coef_3                             REAL,
    hole_limit_max                          REAL,
    hole_limit_min                          REAL,
    counter_coef_1                          REAL,
    counter_coef_2                          REAL,
    counter_coef_3                          REAL,
    counter_limit_max                       REAL,
    counter_limit_min                       REAL,

    start_gcode                             TEXT,
    end_gcode                               TEXT,

    default_colour_hex                      TEXT,

    source                                  TEXT NOT NULL DEFAULT 'Manual',
    source_slicer                           TEXT,
    raw_settings_json                       TEXT,
    source_preset_path                      TEXT,
    version_number                          INTEGER NOT NULL DEFAULT 1,
    version_name                            TEXT,
    is_current_version                      INTEGER NOT NULL DEFAULT 1,
    notes                                   TEXT,
    created_at                              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
